# Generated by Django 4.0.7 on 2022-09-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='document_type',
        ),
    ]
