# Generated by Django 4.0.7 on 2022-09-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='document_type',
            field=models.CharField(choices=[('CC', 'Cedula Ciudanida'), ('TI', 'Tarjeta Identidad'), ('NUIP', 'Registo Civil'), ('CE', 'Cedula Extrajera'), ('NN', 'Nn')], default='NN', max_length=4),
        ),
    ]
